#pragma once

// C++ Standard Library includes
#include <memory>
#include <string>

namespace LibSgfcPlusPlus
{
  // Forward declarations
  class ISgfcSgfContent;

  /// @brief The SgfcSaveStream class provides access to the content of the save
  /// stream that was generated by SGFC during its most recent save operation.
  ///
  /// An SGFC save operation generates SGF content as a stream. Depending on
  /// the processing parameters the save operation migh split its input buffer
  /// into multiple distinct pieces of SGF content. To achieve this goal the
  /// save operation captures the save stream content whenever it has finished
  /// generating a particular piece of SGF content, then resets the stream for
  /// the next piece. SgfcSaveStream makes the SGF content pieces available
  /// individually, together with a file name suggested by SGFC.
  ///
  /// SgfcSaveStream acquires the save stream content immediately upon
  /// construction, then clears the save stream in SGFC. This means that if two
  /// SgfcSaveStream objects are constructed in a row, the second object will
  /// see an empty save stream.
  class SgfcSaveStream
  {
  public:
    SgfcSaveStream();
    virtual ~SgfcSaveStream();

    /// @brief Returns the save stream content that SgfcSaveStream acquired
    /// during construction, split into distinct pieces of SGF content.
    std::vector<std::shared_ptr<ISgfcSgfContent>> GetSgfContents() const;

  private:
    std::vector<std::shared_ptr<ISgfcSgfContent>> sgfContents;

    void MakeSgfContents(
      const std::vector<std::string>& fileContents,
      const std::vector<std::string>& fileNames);
  };
}
