set (
  SOURCES
  main.cpp
  document/SgfcDocumentTest.cpp
  document/SgfcGameTest.cpp
  document/SgfcNodeTest.cpp
  document/SgfcNodeTraitsTest.cpp
  document/SgfcTreeBuilderTest.cpp
  game/SgfcDateTest.cpp
  game/SgfcGameResultTest.cpp
  game/SgfcRoundInformationTest.cpp
  game/go/SgfcGoMoveTest.cpp
  game/go/SgfcGoPlayerRankTest.cpp
  game/go/SgfcGoPointTest.cpp
  game/go/SgfcGoRulesetTest.cpp
  game/go/SgfcGoStoneTest.cpp
  parsing/SgfcPropertyDecoderTest.cpp
  parsing/SgfcValueConverterTest.cpp
  sgfc/argument/SgfcArgumentsTest.cpp
  sgfc/argument/SgfcArgumentTest.cpp
  sgfc/backend/SgfcBackendControllerTest.cpp
  sgfc/backend/SgfcBackendDataWrapperTest.cpp
  sgfc/frontend/EncodingTest.cpp
  sgfc/frontend/SgfcCommandLineTest.cpp
  sgfc/frontend/SgfcDocumentReaderTest.cpp
  sgfc/frontend/SgfcDocumentWriterTest.cpp
  sgfc/message/SgfcMessageStreamTest.cpp
  sgfc/message/SgfcMessageTest.cpp
  sgfc/save/SgfcSaveStreamTest.cpp
  sgfc/save/SgfcSgfContentTest.cpp
  ${SOURCES_LIST_FILE_NAME}
  AssertHelperFunctions.h
  AssertHelperFunctions.cpp
  SetupHelperFunctions.h
  SetupHelperFunctions.cpp
  TestDataGenerator.cpp
  TestDataGenerator.h
)
