// -----------------------------------------------------------------------------
// Copyright 2020 Patrick Näf (herzbube@herzbube.ch)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------

#pragma once

// C++ Standard Library includes
#include <memory>
#include <vector>

namespace LibSgfcPlusPlus
{
  // Forward declarations
  class ISgfcMessage;

  /// @brief The SgfcMessageStream class captures the stream of messages that
  /// is generated by SGFC.
  ///
  /// @ingroup internals
  /// @ingroup sgfc-message
  ///
  /// SgfcMessageStream starts to capture the stream of SGFC messages
  /// immediately upon construction. Capturing stops only when the
  /// SgfcMessageStream object is destroyed. A client can access the messages
  /// captured so far during the lifetime of the SgfcMessageStream object by
  /// invoking its GetMessages() method.
  ///
  /// Only one SgfcMessageStream can be active at any given time.
  class SgfcMessageStream
  {
  public:
    /// @brief Initializes a newly constructed SgfcMessageStream object.
    /// The object immediately starts capturing the SGFC message stream.
    ///
    /// @exception std::logic_error Is thrown if another SgfcMessageStream
    /// object already exists.
    SgfcMessageStream();

    /// @brief Destroys and cleans up the SgfcMessageStream object.
    virtual ~SgfcMessageStream();

    /// @brief Returns a collection of messages captured so far by the
    /// SgfcMessageStream object. The messages appear in the collection in the
    /// order in which they are generated by SGFC. The collection is empty
    /// if SGFC has not generated any messages.
    std::vector<std::shared_ptr<ISgfcMessage>> GetMessagees() const;
  };
}
