var searchData=
[
  ['identifier_20when_20building_20for_20ios_0',['Bundle identifier when building for iOS',['../md__build.html#autotoc_md21',1,'']]],
  ['implementation_1',['Public API vs. private implementation',['../md__principles.html#autotoc_md53',1,'']]],
  ['in_20a_20software_20library_2',['SGFC code reuse in a software library',['../md__sgfc_notes.html#autotoc_md80',1,'']]],
  ['in_20isgfcdocumentreader_3',['UTF-8 support in &lt;span class=&quot;tt&quot;&gt;ISgfcDocumentReader&lt;/span&gt;',['../md__sgf_notes.html#autotoc_md124',1,'']]],
  ['in_20isgfcdocumentwriter_4',['UTF-8 is the default character encoding in &lt;span class=&quot;tt&quot;&gt;ISgfcDocumentWriter&lt;/span&gt;',['../md__sgf_notes.html#autotoc_md125',1,'']]],
  ['include_20directory_5',['Include directory',['../md__project_notes.html#autotoc_md66',1,'']]],
  ['including_6',['Angle syntax vs. quotes syntax when including',['../md__project_notes.html#autotoc_md67',1,'']]],
  ['indentation_20and_20formatting_7',['Indentation and formatting',['../md__coding_guidelines.html#autotoc_md46',1,'']]],
  ['inheritable_20properties_8',['Inheritable properties',['../md__sgf_notes.html#autotoc_md117',1,'']]],
  ['inheritance_9',['Virtual inheritance',['../md__principles.html#autotoc_md61',1,'']]],
  ['install_10',['How to install',['../md__build.html#autotoc_md6',1,'']]],
  ['install_20check_20testing_20framework_11',['Install &lt;span class=&quot;tt&quot;&gt;check&lt;/span&gt; testing framework',['../md__sgfc_notes.html#autotoc_md88',1,'']]],
  ['install_20the_20api_20documentation_12',['How to generate and install the API documentation',['../md__build.html#autotoc_md7',1,'']]],
  ['integrating_20catch2_20into_20the_20build_13',['Integrating Catch2 into the build',['../md__build.html#autotoc_md5',1,'']]],
  ['into_20the_20build_14',['Integrating Catch2 into the build',['../md__build.html#autotoc_md5',1,'']]],
  ['introduction_15',['Introduction',['../md__sgf_notes.html#autotoc_md119',1,'']]],
  ['ios_16',['iOS',['../md__build.html#autotoc_md21',1,'Bundle identifier when building for iOS'],['../md__build.html#autotoc_md19',1,'Codesigning when building for iOS'],['../md__build.html#autotoc_md15',1,'Cross-compiling for iOS'],['../md__build.html#autotoc_md20',1,'Deployment target when building for iOS']]],
  ['ios_5finstall_5fcombined_17',['The old way: &lt;span class=&quot;tt&quot;&gt;IOS_INSTALL_COMBINED&lt;/span&gt;',['../md__build.html#autotoc_md16',1,'']]],
  ['is_20it_18',['What is it?',['../index.html#autotoc_md127',1,'']]],
  ['is_20recommended_20for_20programmatically_20creating_20isgfcdocument_20object_20trees_19',['UTF-8 is recommended for programmatically creating ISgfcDocument object trees',['../md__sgf_notes.html#autotoc_md123',1,'']]],
  ['is_20the_20default_20character_20encoding_20in_20isgfcdocumentwriter_20',['UTF-8 is the default character encoding in &lt;span class=&quot;tt&quot;&gt;ISgfcDocumentWriter&lt;/span&gt;',['../md__sgf_notes.html#autotoc_md125',1,'']]],
  ['isgfcdocument_20object_20trees_21',['UTF-8 is recommended for programmatically creating ISgfcDocument object trees',['../md__sgf_notes.html#autotoc_md123',1,'']]],
  ['isgfcdocumentreader_22',['UTF-8 support in &lt;span class=&quot;tt&quot;&gt;ISgfcDocumentReader&lt;/span&gt;',['../md__sgf_notes.html#autotoc_md124',1,'']]],
  ['isgfcdocumentwriter_23',['UTF-8 is the default character encoding in &lt;span class=&quot;tt&quot;&gt;ISgfcDocumentWriter&lt;/span&gt;',['../md__sgf_notes.html#autotoc_md125',1,'']]],
  ['issue_20list_24',['issue list',['../md__change_log.html#autotoc_md29',1,'GitHub issue list'],['../md__change_log.html#autotoc_md36',1,'GitHub issue list']]],
  ['it_25',['What is it?',['../index.html#autotoc_md127',1,'']]],
  ['it_20does_20today_26',['Why document writing works like it does today',['../md__sgfc_notes.html#autotoc_md79',1,'']]],
  ['it_20s_20not_27',['What it&apos;s not',['../index.html#autotoc_md128',1,'']]]
];
