var searchData=
[
  ['s_20not_0',['What it&apos;s not',['../index.html#autotoc_md128',1,'']]],
  ['s_20old_20new_20build_20system_1',['Xcode&apos;s old/new build system',['../md__build.html#autotoc_md18',1,'']]],
  ['safe_2',['ASCII-compatible vs. ASCII-safe',['../md__sgf_notes.html#autotoc_md121',1,'']]],
  ['sample_20code_3',['Sample code',['../md__build.html#autotoc_md8',1,'']]],
  ['september_2020_202020_4',['September 20 2020',['../md__change_log.html#autotoc_md40',1,'']]],
  ['sgf_20format_5',['SGF format',['../md__sgf_notes.html#autotoc_md96',1,'']]],
  ['sgf_20notes_6',['SGF notes',['../md__sgf_notes.html',1,'']]],
  ['sgf_20type_20number_7',['Value range of properties with SGF type &lt;span class=&quot;tt&quot;&gt;Number&lt;/span&gt;',['../md__sgf_notes.html#autotoc_md100',1,'']]],
  ['sgf_20type_20real_8',['Precision of properties with SGF type &lt;span class=&quot;tt&quot;&gt;Real&lt;/span&gt;',['../md__sgf_notes.html#autotoc_md99',1,'']]],
  ['sgfc_20code_20reuse_20in_20a_20software_20library_9',['SGFC code reuse in a software library',['../md__sgfc_notes.html#autotoc_md80',1,'']]],
  ['sgfc_20messages_10',['SGFC messages',['../md__principles.html#autotoc_md58',1,'']]],
  ['sgfc_20notes_11',['SGFC notes',['../md__sgfc_notes.html',1,'']]],
  ['sgfc_20on_20macos_12',['Building SGFC on macOS',['../md__sgfc_notes.html#autotoc_md87',1,'']]],
  ['sgfc_20patches_13',['SGFC Patches',['../md__sgfc_patches.html',1,'']]],
  ['simpletext_20and_20text_20property_20values_14',['SimpleText and Text property values',['../md__sgf_notes.html#autotoc_md104',1,'']]],
  ['software_20library_15',['SGFC code reuse in a software library',['../md__sgfc_notes.html#autotoc_md80',1,'']]],
  ['special_20properties_16',['Handling of special properties',['../md__sgfc_notes.html#autotoc_md84',1,'']]],
  ['specific_20c_20types_17',['Go-specific C++ types',['../md__sgf_notes.html#autotoc_md113',1,'']]],
  ['steps_18',['Release steps',['../md__release_steps.html',1,'']]],
  ['stone_20property_20values_19',['Move/Point/Stone property values',['../md__sgf_notes.html#autotoc_md105',1,'']]],
  ['structure_20',['Code structure',['../md__coding_guidelines.html#autotoc_md49',1,'']]],
  ['studio_21',['Visual Studio',['../md__build.html#autotoc_md12',1,'']]],
  ['stuff_22',['Other stuff',['../md__coding_guidelines.html#autotoc_md51',1,'']]],
  ['summary_23',['Summary',['../md__sgf_notes.html#autotoc_md103',1,'']]],
  ['support_24',['Go support',['../md__sgf_notes.html#autotoc_md112',1,'']]],
  ['support_20for_20downstream_20projects_25',['CMake support for downstream projects',['../md__build.html#autotoc_md22',1,'']]],
  ['support_20in_20isgfcdocumentreader_26',['UTF-8 support in &lt;span class=&quot;tt&quot;&gt;ISgfcDocumentReader&lt;/span&gt;',['../md__sgf_notes.html#autotoc_md124',1,'']]],
  ['syntax_20vs_20quotes_20syntax_20when_20including_27',['Angle syntax vs. quotes syntax when including',['../md__project_notes.html#autotoc_md67',1,'']]],
  ['syntax_20when_20including_28',['Angle syntax vs. quotes syntax when including',['../md__project_notes.html#autotoc_md67',1,'']]],
  ['system_29',['system',['../md__build.html',1,'Project build system'],['../index.html#autotoc_md130',1,'Project build system'],['../md__build.html#autotoc_md18',1,'Xcode&apos;s old/new build system']]]
];
