var searchData=
[
  ['pass_20moves_20for_20go_20games_0',['Pass moves for Go games',['../md__sgfc_notes.html#autotoc_md77',1,'Pass moves for Go games'],['../md__sgf_notes.html#autotoc_md114',1,'Pass moves for Go games']]],
  ['patches_1',['SGFC Patches',['../md__sgfc_patches.html',1,'']]],
  ['patches_2',['How to apply the patches',['../md__sgfc_patches.html#autotoc_md92',1,'']]],
  ['patches_20001_20015_3',['Patches 001-015',['../md__sgfc_patches.html#autotoc_md93',1,'']]],
  ['point_20lists_4',['point lists',['../md__sgfc_notes.html#autotoc_md78',1,'Compressed point lists'],['../md__sgf_notes.html#autotoc_md108',1,'Compressed point lists'],['../md__sgf_notes.html#autotoc_md115',1,'Compressed point lists']]],
  ['point_20stone_20property_20values_5',['Move/Point/Stone property values',['../md__sgf_notes.html#autotoc_md105',1,'']]],
  ['pre_20ff4_20properties_6',['Pre-FF4 properties',['../md__sgf_notes.html#autotoc_md98',1,'']]],
  ['precision_20of_20properties_20with_20sgf_20type_20real_7',['Precision of properties with SGF type &lt;span class=&quot;tt&quot;&gt;Real&lt;/span&gt;',['../md__sgf_notes.html#autotoc_md99',1,'']]],
  ['preprocessor_8',['Preprocessor',['../md__coding_guidelines.html#autotoc_md47',1,'']]],
  ['prerequisites_9',['Prerequisites',['../md__build.html#autotoc_md1',1,'']]],
  ['principles_10',['Library design and working principles',['../md__principles.html',1,'']]],
  ['private_20implementation_11',['Public API vs. private implementation',['../md__principles.html#autotoc_md53',1,'']]],
  ['products_12',['Enabling/disabling build products',['../md__build.html#autotoc_md9',1,'']]],
  ['programmatically_20creating_20isgfcdocument_20object_20trees_13',['UTF-8 is recommended for programmatically creating ISgfcDocument object trees',['../md__sgf_notes.html#autotoc_md123',1,'']]],
  ['project_20build_20system_14',['Project build system',['../md__build.html',1,'Project build system'],['../index.html#autotoc_md130',1,'Project build system']]],
  ['project_20names_3a_20libsgfc_20and_20libsgfcplusplus_15',['Two project names: libsgfc++ and libsgfcplusplus',['../md__project_notes.html#autotoc_md63',1,'']]],
  ['project_20notes_16',['Project notes',['../md__project_notes.html',1,'']]],
  ['projects_17',['CMake support for downstream projects',['../md__build.html#autotoc_md22',1,'']]],
  ['properties_18',['properties',['../md__sgfc_notes.html#autotoc_md84',1,'Handling of special properties'],['../md__sgf_notes.html#autotoc_md117',1,'Inheritable properties'],['../md__sgf_notes.html#autotoc_md98',1,'Pre-FF4 properties'],['../md__sgf_notes.html#autotoc_md116',1,'The &quot;KI&quot; and &quot;KM&quot; properties']]],
  ['properties_20with_20no_20value_19',['Properties with no value',['../md__sgf_notes.html#autotoc_md97',1,'']]],
  ['properties_20with_20sgf_20type_20number_20',['Value range of properties with SGF type &lt;span class=&quot;tt&quot;&gt;Number&lt;/span&gt;',['../md__sgf_notes.html#autotoc_md100',1,'']]],
  ['properties_20with_20sgf_20type_20real_21',['Precision of properties with SGF type &lt;span class=&quot;tt&quot;&gt;Real&lt;/span&gt;',['../md__sgf_notes.html#autotoc_md99',1,'']]],
  ['property_22',['property',['../md__sgfc_notes.html#autotoc_md85',1,'The &quot;AP&quot; property'],['../md__sgfc_notes.html#autotoc_md86',1,'The &quot;KI&quot; property']]],
  ['property_20value_20validation_23',['Property value validation',['../md__sgf_notes.html#autotoc_md101',1,'']]],
  ['property_20values_24',['property values',['../md__sgf_notes.html#autotoc_md105',1,'Move/Point/Stone property values'],['../md__sgf_notes.html#autotoc_md104',1,'SimpleText and Text property values']]],
  ['public_20api_20vs_20private_20implementation_25',['Public API vs. private implementation',['../md__principles.html#autotoc_md53',1,'']]],
  ['publish_20api_20documentation_26',['Generate and publish API documentation',['../md__release_steps.html#autotoc_md72',1,'']]]
];
