var searchData=
[
  ['target_20when_20building_20for_20ios_0',['Deployment target when building for iOS',['../md__build.html#autotoc_md20',1,'']]],
  ['technical_20changes_1',['Technical changes',['../md__change_log.html#autotoc_md28',1,'Technical changes'],['../md__change_log.html#autotoc_md35',1,'Technical changes']]],
  ['test_2',['How to test',['../md__build.html#autotoc_md3',1,'']]],
  ['test_20cases_3',['Test cases',['../md__sgf_notes.html#autotoc_md106',1,'Test cases'],['../md__sgf_notes.html#autotoc_md111',1,'Test cases']]],
  ['testing_20framework_4',['Install &lt;span class=&quot;tt&quot;&gt;check&lt;/span&gt; testing framework',['../md__sgfc_notes.html#autotoc_md88',1,'']]],
  ['tests_5',['Executing tests',['../md__build.html#autotoc_md4',1,'']]],
  ['text_20property_20values_6',['SimpleText and Text property values',['../md__sgf_notes.html#autotoc_md104',1,'']]],
  ['the_20ap_20property_7',['The &quot;AP&quot; property',['../md__sgfc_notes.html#autotoc_md85',1,'']]],
  ['the_20api_20documentation_8',['How to generate and install the API documentation',['../md__build.html#autotoc_md7',1,'']]],
  ['the_20build_9',['Integrating Catch2 into the build',['../md__build.html#autotoc_md5',1,'']]],
  ['the_20default_20character_20encoding_20in_20isgfcdocumentwriter_10',['UTF-8 is the default character encoding in &lt;span class=&quot;tt&quot;&gt;ISgfcDocumentWriter&lt;/span&gt;',['../md__sgf_notes.html#autotoc_md125',1,'']]],
  ['the_20export_20header_20file_11',['The export header file',['../md__project_notes.html#autotoc_md64',1,'']]],
  ['the_20ki_20and_20km_20properties_12',['The &quot;KI&quot; and &quot;KM&quot; properties',['../md__sgf_notes.html#autotoc_md116',1,'']]],
  ['the_20ki_20property_13',['The &quot;KI&quot; property',['../md__sgfc_notes.html#autotoc_md86',1,'']]],
  ['the_20main_20function_14',['The &lt;span class=&quot;tt&quot;&gt;main()&lt;/span&gt; function',['../md__sgfc_notes.html#autotoc_md81',1,'']]],
  ['the_20new_20way_3a_20xcframework_15',['The new way: XCFramework',['../md__build.html#autotoc_md17',1,'']]],
  ['the_20old_20way_3a_20ios_5finstall_5fcombined_16',['The old way: &lt;span class=&quot;tt&quot;&gt;IOS_INSTALL_COMBINED&lt;/span&gt;',['../md__build.html#autotoc_md16',1,'']]],
  ['the_20patches_17',['How to apply the patches',['../md__sgfc_patches.html#autotoc_md92',1,'']]],
  ['the_20release_18',['the release',['../md__release_steps.html#autotoc_md69',1,'Before the release'],['../md__release_steps.html#autotoc_md73',1,'Make the release']]],
  ['to_20apply_20the_20patches_19',['How to apply the patches',['../md__sgfc_patches.html#autotoc_md92',1,'']]],
  ['to_20build_20',['How to build',['../md__build.html#autotoc_md2',1,'']]],
  ['to_20generate_20and_20install_20the_20api_20documentation_21',['How to generate and install the API documentation',['../md__build.html#autotoc_md7',1,'']]],
  ['to_20install_22',['How to install',['../md__build.html#autotoc_md6',1,'']]],
  ['to_20test_23',['How to test',['../md__build.html#autotoc_md3',1,'']]],
  ['today_24',['Why document writing works like it does today',['../md__sgfc_notes.html#autotoc_md79',1,'']]],
  ['todo_20list_25',['Todo List',['../todo.html',1,'']]],
  ['trees_26',['UTF-8 is recommended for programmatically creating ISgfcDocument object trees',['../md__sgf_notes.html#autotoc_md123',1,'']]],
  ['two_20project_20names_3a_20libsgfc_20and_20libsgfcplusplus_27',['Two project names: libsgfc++ and libsgfcplusplus',['../md__project_notes.html#autotoc_md63',1,'']]],
  ['type_20number_28',['Value range of properties with SGF type &lt;span class=&quot;tt&quot;&gt;Number&lt;/span&gt;',['../md__sgf_notes.html#autotoc_md100',1,'']]],
  ['type_20real_29',['Precision of properties with SGF type &lt;span class=&quot;tt&quot;&gt;Real&lt;/span&gt;',['../md__sgf_notes.html#autotoc_md99',1,'']]],
  ['types_30',['Go-specific C++ types',['../md__sgf_notes.html#autotoc_md113',1,'']]]
];
