#pragma once

namespace LibSgfcPlusPlus
{
  /// @brief SgfcBackendDataState enumerates the states that the SGFInfo data
  /// structure encapsulated by SgfcBackendDataWrapper can have.
  ///
  /// @ingroup internals
  /// @ingroup sgfc-backend
  enum class SgfcBackendDataState
  {
    /// @brief The SGFInfo data structure is allocated and empty. It contains
    /// neither a raw file buffer with SGF content, nor any child data
    /// structures.
    NotLoaded,

    /// @brief The SGFInfo data structure is allocated and contains a raw file
    /// buffer with SGF content, but no child data structures. The SGF content
    /// in the file buffer was either loaded from an actual file in the file
    /// system, or generated from the content of an ISgfcDocument.
    PartiallyLoaded,

    /// @brief The SGFInfo data structure is allocated and contains a raw file
    /// buffer with SGF content plus a full set of child data structures
    /// generated by parsing the SGF content.
    FullyLoaded,
  };

}
