// -----------------------------------------------------------------------------
// Copyright 2020 Patrick Näf (herzbube@herzbube.ch)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------

#pragma once

namespace LibSgfcPlusPlus
{
  /// @brief SgfcBackendDataState enumerates the states that the SGFInfo data
  /// structure encapsulated by SgfcBackendDataWrapper can have.
  ///
  /// @ingroup internals
  enum class SgfcBackendDataState
  {
    /// @brief The SGFInfo data structure is allocated and empty. It contains
    /// neither a raw file buffer with SGF content, nor any child data
    /// structures.
    NotLoaded,

    /// @brief The SGFInfo data structure is allocated and contains a raw file
    /// buffer with SGF content, but no child data structures. The SGF content
    /// in the file buffer was either loaded from an actual file in the file
    /// system, generated from the content of an ISgfcDocument, or passed to
    /// the library by the library client.
    PartiallyLoaded,

    /// @brief The SGFInfo data structure is allocated and contains a raw file
    /// buffer with SGF content plus a full set of child data structures
    /// generated by parsing the SGF content.
    FullyLoaded,
  };
}
