// -----------------------------------------------------------------------------
// Copyright 2020 Patrick Näf (herzbube@herzbube.ch)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------

#pragma once

// Project includes
#include "../../../include/ISgfcMessage.h"
#include "SgfcBackendDataWrapper.h"

// C++ Standard Library includes
#include <memory>
#include <vector>

namespace LibSgfcPlusPlus
{
  /// @brief The SgfcBackendLoadResult class provides access to the result of
  /// a load operation performed by SgfcBackendController.
  ///
  /// @ingroup internals
  /// @ingroup sgfc-backend
  class SgfcBackendLoadResult
  {
  public:
    /// @brief Initializes a newly constructed SgfcBackendLoadResult object
    /// with the specified results.
    SgfcBackendLoadResult(
      std::vector<std::shared_ptr<ISgfcMessage>> parseResult,
      std::shared_ptr<SgfcBackendDataWrapper> sgfDataWrapper);

    /// @brief Destroys and cleans up the SgfcBackendLoadResult object.
    virtual ~SgfcBackendLoadResult();

    /// @brief Returns a collection of ISgfcMessage objects which together form
    /// the parse result of the load operation. The messages appear in the order
    /// in which they were generated by SGFC.
    std::vector<std::shared_ptr<ISgfcMessage>> GetParseResult() const;

    /// @brief Returns a pointer to the SGF data that was generated by SGFC.
    std::shared_ptr<SgfcBackendDataWrapper> GetSgfDataWrapper() const;

  private:
    std::vector<std::shared_ptr<ISgfcMessage>> parseResult;
    std::shared_ptr<SgfcBackendDataWrapper> sgfDataWrapper;
  };
}
