#pragma once

// Project includes
#include "ISgfcMessage.h"
#include "SgfcExitCode.h"

// Project includes (generated)
#include <SgfcPlusPlusExport.h>

// C++ Standard Library includes
#include <memory>
#include <vector>

namespace LibSgfcPlusPlus
{
  /// @brief The ISgfcDocumentWriteResult interface provides access to the
  /// result of a write operation performed by ISgfcDocumentWriter.
  ///
  /// ISgfcDocumentWriteResult is immutable, i.e. once the
  /// ISgfcDocumentWriteResult object is constructed it cannot be changed.
  class SGFCPLUSPLUS_EXPORT ISgfcDocumentWriteResult
  {
  public:
    /// @brief Initializes a newly constructed ISgfcDocumentWriteResult object.
    ISgfcDocumentWriteResult();

    /// @brief Destroys and cleans up the ISgfcDocumentWriteResult object.
    virtual ~ISgfcDocumentWriteResult();

    /// @brief Returns an SgfcExitCode value that best fits the result of the
    /// write operation. The numeric value of the SgfcExitCode corresponds to
    /// one of the exit codes of SGFC.
    virtual SgfcExitCode GetExitCode() const = 0;

    /// @brief Returns a collection of ISgfcMessage objects which together form
    /// the parse result of the write operation. The messages appear in the
    /// order in which they were generated by SGFC.
    virtual std::vector<std::shared_ptr<ISgfcMessage>> GetParseResult() const = 0;
  };
}
