#pragma once

// Project includes (generated)
#include <SgfcPlusPlusExport.h>

// C++ Standard Library includes
#include <string>

namespace LibSgfcPlusPlus
{
  /// @brief The ISgfcSgfContent interface represents a distinct piece of SGF
  /// content that is generated by SGFC when it performs a save operation.
  /// ISgfcSgfContent objects are immutable.
  class SGFCPLUSPLUS_EXPORT ISgfcSgfContent
  {
  public:
    /// @brief Initializes a newly constructed ISgfcSgfContent object.
    ISgfcSgfContent();

    /// @brief Destroys and cleans up the ISgfcSgfContent object.
    virtual ~ISgfcSgfContent();

    /// @brief Returns the SGF content.
    virtual std::string GetSgfContent() const = 0;

    /// @brief Returns the file name that SGFC would have used to save the SGF
    /// content to the filesystem.
    virtual std::string GetFileName() const = 0;
  };
}
