#pragma once

namespace LibSgfcPlusPlus
{
  /// @brief SgfcMessageType enumerates all message types generated by SGFC.
  ///
  /// @note If you know the SGFC documentation very well, then you may note
  /// that there is no message type "FatalError". The reason is that the
  /// library converts fatal error messages into exceptions.
  enum class SgfcMessageType
  {
    /// @brief The message describes something that is likely a minor problem
    /// in the SGF data parsed by SGFC. The message may also document a
    /// corrective action taken by SGFC.
    Warning,

    /// @brief The message describes an error in the SGF data parsed by SGFC.
    Error,
  };
}
