// -----------------------------------------------------------------------------
// Copyright 2020 Patrick Näf (herzbube@herzbube.ch)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------

#pragma once

// Project includes (generated)
#include "SgfcPlusPlusExport.h"

namespace LibSgfcPlusPlus
{
  /// @brief SgfcMessageType enumerates all message types generated by SGFC.
  ///
  /// @ingroup public-api
  enum class SGFCPLUSPLUS_EXPORT SgfcMessageType
  {
    /// @brief The message describes something that is likely a minor problem
    /// in the SGF data parsed by SGFC. The message may also document a
    /// corrective action taken by SGFC.
    Warning,

    /// @brief The message describes an error in the SGF data parsed by SGFC.
    Error,

    /// @brief The message describes a fatal error in the SGF data parsed by
    /// SGFC, or it describes a fatal error that occurred during the SGFC
    /// operation (e.g. a file handling error).
    FatalError,
  };
}
