// -----------------------------------------------------------------------------
// Copyright 2020 Patrick Näf (herzbube@herzbube.ch)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------

#pragma once

// Project includes (generated)
#include "SgfcPlusPlusExport.h"

// C++ Standard Library includes
#include <limits>

namespace LibSgfcPlusPlus
{
  /// @brief SgfcMessageID enumerates the message identification numbers that
  /// an ISgfcMessage object can have.
  ///
  /// @ingroup public-api
  ///
  /// Every enumerator has an underlying numeric value. Library clients should
  /// not rely on a specific value as they can change without notice. The only
  /// guarantee given is that positive values (including zero) are for messages
  /// that are generated by SGFC, and negative values are for messages generated
  /// by libsgfc++.
  ///
  /// Please consult the SGFC documentation if in doubt about the meaning of a
  /// message generated by SGFC. SGFC calls them "error codes".
  enum class SGFCPLUSPLUS_EXPORT SgfcMessageID
  {
    /// @name SGFC messages
    //@{
    /// @brief SGFC was invoked with an argument that is neither an option,
    /// an input file or an output file.
    ///
    /// This message cannot actually occur when using SGFC via libsgfc++.
    UnknownCommand = 1,
    /// @brief SGFC was invoked with an argument that is not a supported short
    /// command line option.
    ///
    /// This message cannot actually occur when using SGFC via libsgfc++.
    UnknownCommandLineOption = 2,
    /// @brief SGFC was unable to open the source file.
    CouldNotOpenSourceFile = 3,
    /// @brief SGFC was unable to read the source file.
    CouldNotReadSourceFile = 4,
    /// @brief SGFC was unable to allocate enough memory.
    MemoryAllocationFailed = 5,
    /// @brief SGFC found what looks like SGF data before a game tree, i.e.
    /// before the character sequence "(;".
    SgfDataBeforeGameTree = 6,
    /// @brief SGFC was unable to find any SGF data.
    NoSgfData = 7,
    /// @brief SGFC found illegal characters in between SGF markup.
    IllegalCharacters = 8,
    /// @brief SGFC found a variation that is missing the closing paranthesis.
    VariationNestingIncomplete = 9,
    /// @brief SGFC parsed incomplete SGF content.
    UnexpectedEndOfFile = 10,
    /// @brief SGFC found a property identifier that is too long. This may
    /// indicate that the content is not SGF.
    PropertyIdentifierTooLong = 11,
    /// @brief SGFC found (and ignored) an empty variation.
    EmptyVariationIgnored = 12,
    /// @brief SGFC found a property with more than one value although it can
    /// have only one value. SGFC ignored the surplus values.
    SurplusValuesIgnored = 13,
    /// @brief SGFC found (and deleted) an illegal property value.
    IllegalValueDeleted = 14,
    /// @brief SGFC found (and corrected) an illegal single property value.
    IllegalSingleValueCorrected = 15,
    /// @brief SGFC found a property identifier that contains lowercase
    /// characters. This message is only generated for SGF content in FF4
    /// format.
    PropertyIdentifierWithLowercaseCharacter = 16,
    /// @brief SGFC found (and deleted) an empty property value.
    EmptyValueDeleted = 17,
    /// @brief SGFC found (and took action) a root property with an illegal
    /// value. The value may have been deleted or corrected.
    IllegalRootPropertyValue = 18,
    /// @brief SGFC found a game type that is not Go. Move and position values
    /// are not checked.
    GameIsNotGo = 19,
    /// @brief SGFC found (and ignored) a property without any values.
    PropertyWithoutValuesIgnored = 20,
    /// @brief SGFC found (and ignored) an illegal variation start.
    IllegalVariationStartIgnored = 21,
    /// @brief SGFC found (and deleted) a zero byte.
    ZeroByteDeleted = 22,
    /// @brief SGFC found a property that expects composed values but the
    /// actual values are one or more single values. SGFC deleted the single
    /// value(s).
    NonComposedValueDeleted = 23,
    /// @brief SGFC found a move property in a game tree's root node and split
    /// the root node into two, with the move property being in the second node.
    MoveInRootNodeSplit = 24,
    /// @brief SGFC found (and corrected) an illegal composed property value.
    IllegalComposedValueCorrected = 25,
    /// @brief SGFC was unable to open the destination file.
    CouldNotOpenDestinationFile = 26,
    /// @brief SGFC was unable to write the destination file.
    CouldNotWriteDestinationFile = 27,
    /// @brief SGFC found (and deleted) a property that already exists.
    DuplicatePropertyDeleted = 28,
    /// @brief SGFC found (and deleted) an obsolete property.
    ///
    /// @see SgfcArgumentType::DeleteObsoleteProperties.
    ObsoletePropertyDeleted = 29,
    /// @brief SGFC found a node that contains both setup and move properties.
    MixedSetupAndMove = 30,
    /// @brief SGFC found a property with an identifier that consists of more
    /// than two uppercase characters.
    LongPropertyIdentifier = 31,
    /// @brief SGFC found (and deleted) a root property in a node that is not
    /// the root node.
    RootPropertyDeleted = 32,
    /// @brief SGFC found a game info property that is illegally formatted.
    GameInfoPropertyWithIllegalFormat = 33,
    /// @brief SGFC did not save the SGF content because parsing generated
    /// one or more critical errors.
    ///
    /// This message cannot actually occur when using SGFC via libsgfc++.
    NotSavedBecauseOfCriticalErrors = 34,
    /// @brief SGFC found (and deleted) an unknown (i.e. a custom) property.
    UnknownPropertyDeleted = 35,
    /// @brief SGFC did not find a semicolon in front of what looks like a
    /// game tree.
    ///
    /// @see SgfcArgumentType::BeginningOfSgfData.
    MissingSemicolonAtGameTreeStart = 36,
    /// @brief SGFC found a node that contains moves by both the black and the
    /// white player. The node was split into two, with the black move and one
    /// with the white move.
    BlackAndWhiteMoveSplit = 37,
    /// @brief SGFC found a position that is not unique, i.e. some combination
    /// of properties that operate on the same point with contradicting
    /// meaning (e.g. different markup or stones on the same point).
    PositionNotUnique = 38,
    /// @brief SGFC found (and deleted) a property that adds a stone to the
    /// board but the addition has no effect.
    AddStoneDeleted = 39,
    /// @brief SGFC found a property that is not defined in the version of the
    /// SGF standard denoted by the FF property in the SGF content. The
    /// property may have been converted or even deleted.
    PropertyNotDefinedInFF = 40,
    /// @brief SGFC found (and deleted) an annotation property whose value
    /// contradicts a previous property.
    ContradictingAnnotationDeleted = 41,
    /// @brief SGFC found a combination of certain properties and converted them
    /// to another property.
    ///
    /// Combinations of TE and BM get converted to DO and IT.
    CombinationOfPropertiesConverted = 42,
    /// @brief SGFC found (and deleted) a move annotation property in a node
    /// that didn't also contain a move property.
    MoveAnnotationDeleted = 43,
    /// @brief SGFC found (and deleted) a game info property outside of a
    /// game info node.
    GameInfoDeleted = 44,
    /// @brief SGFC found different file formats in the SGF content.
    DifferentFileFormats = 45,
    /// @brief SGFC found an unknown file format in the SGF content. SGFC can
    /// handle only file formats up to FF4.
    UnknownFileFormat = 46,
    /// @brief SGFC found (and corrected) an SZ property with two values
    /// defining a rectangular board, but the two values were the same, so
    /// SGFC corrected this to an SZ property with a single value defining
    /// a square board.
    SquareBoardSizeCorrected = 47,
    /// @brief SGFC was invoked without a source file argument.
    ///
    /// This message cannot actually occur when using SGFC via libsgfc++.
    SourceFileNotSpecified = 48,
    /// @brief SGFC was invoked with an argument that takes a parameter, but
    /// the specified parameter is illegal for the argument.
    BadCommandLineOptionParameter = 49,
    /// @brief SGFC found (and corrected) a board size property with a value
    /// that is too large.
    TooLargeBoardSizeCorrected = 50,
    /// @brief SGFC found a feature that is not defined in the particular file
    /// format of the SGF content.
    UsedFeatureNotDefinedInFileFormat = 51,
    /// @brief SGFC found one of various error cases related to the VW property.
    /// The exact problem is in the message text.
    ViewError = 52,
    /// @brief SGFC found different game types in the SGF content.
    DifferentGameTypes = 53,
    /// @brief SGFC found (and deleted) one or more values not associated with
    /// any property.
    ValuesWithoutPropertyDeleted = 54,
    /// @brief SGFC found (and deleted) an empty node.
    ///
    /// @see SgfcArgumentType::DeleteEmptyNodes.
    EmptyNodeDeleted = 55,
    /// @brief SGFC found what could possibly be a wrong variation level.
    /// It was unable to take corrective action.
    VariationLevelNotCorrected = 56,
    /// @brief SGFC found a wrong variation level. It was able to take
    /// corrective action.
    VariationLevelCorrected = 57,

    /// @brief SGFC found a forbidden move that played a stone on a point that
    /// is already occupied by another stone.
    ForbiddenMove = 58,
    /// @brief SGFC found (and deleted/converted) an obsolete KI property.
    IntegerKomiDeleted = 59,
    /// @brief SGFC found more than one game tree in the SGF content.
    ///
    /// @see SgfcArgumentType::EnableRestrictiveChecking.
    MoreThanOneGameTree = 60,
    /// @brief SGFC found a HA property whose value differs from the number of
    /// stones that were set up with setup properties.
    ///
    /// @see SgfcArgumentType::EnableRestrictiveChecking.
    HandicapDiffersFromSetup = 61,
    /// @brief SGFC found setup properties in a node that is not the root node.
    ///
    /// @see SgfcArgumentType::EnableRestrictiveChecking.
    SetupStonesOutsideRootNode = 62,
    /// @brief SGFC found two successive moves that have the same color.
    ///
    /// @see SgfcArgumentType::EnableRestrictiveChecking.
    TwoMovesWithSameColor = 63,
    /// @brief SGFC was unable to reorder variations because there were too many
    /// variations in the SGF content.
    VariationReorderFailed = 64,

    /// @brief SGFC found a pass move in the new FF4 style in SGF content that
    /// has an older file format.
    NewStylePassMove = 65,
    /// @brief SGFC found (and fixed) a node that was not in any variation.
    NodeNotInVariation = 66,
    /// @brief SGFC found (and corrected) an illegal variation start.
    IllegalVariationStartCorrected = 21,
    /// @brief SGFC was invoked with an argument that is not a supported long
    /// command line option.
    ///
    /// This message cannot actually occur when using SGFC via libsgfc++.
    UnknownLongCommandLineOption = 68,
    /// @brief Indicates that the message was generated by SGFC, but libsgfc++
    /// was unable to determine the message ID when it parsed the raw message
    /// text.
    ///
    /// This message ID is a positive number in order to satisfy the guarantee
    /// that SGFC-generated messages always have message IDs >= 0. libsgfc++
    /// strives to use a number that is not in the list of message IDs that are
    /// documented by SGFC.
    UnknownSgfcMessageID = std::numeric_limits<int>::max(),
    //@}

    // ----------------------------------------------------------------------

    /// @name libsgfc++ messages
    //@{
    /// @brief Indicates a message without a valid ID. If a message with this
    /// ID is seen by a library client this indicates a coding error in
    /// libsgfc++.
    InvalidMessageID = -1,
    /// @brief Indicates that a fatal error occurred when SGFC parsed arguments,
    /// but libsgfc++ was unable to obtain the fatal error message from SGFC.
    ParseArgumentError = -2,
    /// @brief Indicates a fatal error that occurred while libsgfc++ attempted
    /// to save a piece of SGF content to the filesystem.
    SaveSgfContentToFilesystemError = -3,
    /// @brief Indicates a fatal error that occurred while libsgfc++ attempted
    /// to read a piece of SGF content from the filesystem.
    ReadSgfContentFromFilesystemError = -4,
    /// @brief Indicates a fatal error that occurred while libsgfc++ attempted
    /// to delete a file in the filesystem.
    DeleteFileError = -5,
    /// @brief Indicates a fatal error because memory allocation failed in SGFC.
    OutOfMemoryError = -6,
    /// @brief Indicates a fatal error that occurred while libsgfc++ attempted
    /// to parse SGF content in order to generate a document.
    ///
    /// This is likely to be a data-related issue, such as when libsgfc++
    /// attempts to construct an ISgfcGameTypeProperty or ISgfcBoardSizeProperty
    /// object with invalid property values.
    ParseSgfContentError = -7,
    /// @brief Indicates a fatal interfacing error between libsgfc++ and SGFC.
    ///
    /// Problems can range from simple (but fundamental) things such as an
    /// unexpected @e nullptr in one of the SGFC data structures, to more
    /// complex data-related issues such as when SGFC and libsgfc++ disagree
    /// about the data type(s) of a property value.
    ///
    /// The message text is technical and unlikely to have any meaning for an
    /// end user.
    SGFCInterfacingError = -8,
    //@}
  };
}
