#pragma once

// Project includes (generated)
#include <SgfcPlusPlusExport.h>

namespace LibSgfcPlusPlus
{
  /// @brief SgfcMessageType enumerates all message types generated by SGFC.
  ///
  /// @ingroup public-api
  enum class SGFCPLUSPLUS_EXPORT SgfcMessageType
  {
    /// @brief The message describes something that is likely a minor problem
    /// in the SGF data parsed by SGFC. The message may also document a
    /// corrective action taken by SGFC.
    Warning,

    /// @brief The message describes an error in the SGF data parsed by SGFC.
    Error,

    /// @brief The message describes a fatal error in the SGF data parsed by
    /// SGFC, or it describes a fatal error that occurred during the SGFC
    /// operation (e.g. a file handling error).
    FatalError,
  };
}
