#pragma once

// Project includes
#include "../include/SgfcMessageType.h"
#include "../include/SgfcGameType.h"

// C++ Standard Library includes
#include <string>
#include <regex>

namespace LibSgfcPlusPlus
{
  /// @brief The SgfcConstants class is a container class for constants.
  class SgfcConstants
  {
  public:
    /// @name libsgfc++ constants
    //@{
    static const std::string LibraryName;
    //@}

    /// @name General string constants
    //@{
    static const std::string EmptyString;
    static const std::string SpaceCharacter;
    static const char NewlineCharacter;
    static const std::string IndentationWhitespace;
    //@}

    /// @name String constants defined by the SGF standard to structure the file format
    //@{
    static const std::string GameTreeBeginToken;
    static const std::string GameTreeEndToken;
    static const std::string NodeBeginToken;
    static const std::string PropertyValueBeginToken;
    static const std::string PropertyValueEndToken;
    static const std::string ComposedValueSeparatorToken;
    static const std::string EscapeCharacterToken;
    static const std::string EscapedPropertyValueEndToken;
    static const std::string EscapedComposedValueSeparatorToken;
    static const std::string EscapedEscapeCharacterToken;
    //@}

    /// @name String constants defined by the SGF standard for specific property values
    //@{
    static const std::string NoneString;
    static const std::string DoubleNormalString;
    static const std::string DoubleEmphasizedString;
    static const std::string ColorBlackString;
    static const std::string ColorWhiteString;
    //@}

    /// @name Regular expression constants
    //@{
    static const std::regex EscapedPropertyValueEndTokenRegex;
    static const std::regex EscapedComposedValueSeparatorTokenRegex;
    static const std::regex EscapedEscapeCharacterRegex;
    static const std::regex UnescapedPropertyValueEndTokenRegex;
    static const std::regex UnescapedComposedValueSeparatorTokenRegex;
    static const std::regex UnescapedEscapeCharacterRegex;
    //@}

    /// @name Constants for strings that can appear in messages generated by SGFC
    //@{
    static const std::string LineToken;
    static const std::string ColumnToken;
    static const std::string DashToken;
    static const std::string WarningToken;
    static const std::string ErrorUpperCaseToken;
    static const std::string FatalToken;
    static const std::string ErrorLowerCaseToken;
    static const std::string CriticalToken;
    //@}

    /// @name SGFC command line option string constants
    //@{
    static const std::string ShortOptionPrefix;
    static const std::string LongOptionPrefix;
    static const std::string ShortHelpOption;
    static const std::string LongHelpOption;
    static const std::string VersionOption;
    static const std::string InteractiveModeOption;
    static const std::string WriteFileEvenIfCriticalErrorOccurs;
    static const std::string PrintGameSignature;
    //@}

    /// @name Message IDs for messages generated by libsgfc++
    //@{
    /// @brief This constant is used to indicate a message without a valid ID
    /// but whose origin is not defined. For instance, a default constructed
    /// ISgfcMessage object has this ID.
    static const int InvalidMessageID;
    /// @brief This constant is used when a message that is known to originate
    /// from SGFC is parsed, and its ID cannot be determined from the raw
    /// message text.
    static const int UnknownSgfcMessageID;
    /// @brief Indicates a fatal error due to an SGFC command line argument
    /// that is banned by libsgfc++.
    static const int BannedArgumentMessageID;
    /// @brief Indicates a fatal error that occurred during parsing of the
    /// SGFC command line argument.
    static const int ParseArgumentErrorMessageID;
    //@}

    /// @name Constants for parsing messages generated by SGFC
    //@{
    static const int DefaultMessageID;
    static const SgfcMessageType DefaultMessageType;
    static const int DefaultLineNumber;
    static const int DefaultColumnNumber;
    static const bool DefaultIsCriticalMessage;
    static const std::string DefaultMessageText;
    static const std::string DefaultRawMessageText;
    //@}

    /// @name Constants for defaults defined by the SGF standard
    //@{
    /// @brief The default game type if the SgfcPropertyType::GM property exists
    /// but has no value.
    ///
    /// The SGF standard defines this to be SgfcGameType::Go.
    static const SgfcGameType DefaultGameType;
    //@}
  };
}
