#pragma once

// Project includes
#include "../include/ISgfcMessage.h"

// C++ Standard Library includes
#include <memory>
#include <vector>

namespace LibSgfcPlusPlus
{
  /// @brief The SgfcMessageParser class parses the text of messages that were
  /// generated by SGFC.
  class SgfcMessageParser
  {
  public:
    /// @brief Creates a new ISgfcMessage object by parsing the text of a
    /// message @a rawMessageText that was generated by SGFC.
    ///
    /// Consecutive whitespace characters in @a rawMessageText are condensed
    /// into a single space character.
    static std::shared_ptr<ISgfcMessage> CreateSgfcMessage(const std::string& rawMessageText);

  private:
    static std::vector<std::string> TokenizeRawMessageText(const std::string& rawMessageText);
    static int GetLineOrColumnNumberFromToken(const std::string& token, const std::string& prefixToStrip);
    static int GetMessageID(const std::string& token);
  };
}
